apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
data:
  kibana.yml: |
    ---
    #xpack.security.enabled: "false"
    server.name: kibana
    server.host: '0'
    elasticsearch.hosts: http://elasticsearch:9200
    elasticsearch.requestTimeout: 120000
    server.ssl.certificate: /usr/share/kibana/certs/server.crt
    server.ssl.enabled: true
    server.ssl.key: /usr/share/kibana/certs/server.key
    #server.ssl.enabled: true
    #server.ssl.certificate: /usr/share/kibana/tls/tls.crt
    #server.ssl.key: /usr/share/kibana/tls/tls.key
    #server.ssl.certificateAuthorities: /usr/share/kibana/tls/tls_issuer.crt
